### ISSUE TITLE
Update build instructions

### ISSUE THREAD

**Issue by Vlad777** [memsql/memsql-mesos#3]
Seems I'm missing something, because it's not so straight-forward as "make build-scheduler"

After "make build-scheduler" and starting the resulting image, the following is in stderr and the framework UI shows a blank page:
[WARNING] memsql_framework.ui.server: 404 GET /static/assets/styles.css (10.123.0.31) 0.44ms
[WARNING] memsql_framework.ui.server: 404 GET /static/assets/index.js (10.123.0.31) 0.42ms

Seems some build instructions are missing, like I had to install node and all the dependencies:
npm install graceful-fs, vinyl-source-stream, watchify, envify, reactify, gulp-sass, gulp-task-listing, gulp-notify, node-bourbon
Then, when running gulp watch I still get:
 gulp watch
[19:47:40] Using gulpfile /memsql-mesos/gulpfile.js
[19:47:40] Starting 'watch'...
[19:47:40] Starting 'scss'...
[19:47:40] Finished 'scss' after 12 ms
[19:47:40] Browserify Error { [Error: Cannot find module 'index' from '/memsql-mesos']

Running "source activate" also gives lots of deprecation.
Eventually fails because sh: mysql_config: command not found

**Comment by wsong** [comment]
The mysql_config thing is because you need to install libmysqlclient-dev (if you're on Linux) or you need to run "brew install mysql" (if you're on OS X).  Type in:

```
$ deactivate
$ rm -rf venv/
$ sudo apt-get install libmysqlclient-dev # (or brew install mysql)
$ source activate
```

Then try the whole build process again.

**Comment by Vlad777** [comment]
Would you be able to push a new docker image of the latest build?

--Vlad

**Comment by wsong** [comment]
Done.
