### ISSUE TITLE
file handle limit not set

### ISSUE THREAD

**Issue by Vlad777** [memsql/memsql-mesos#9]
Despite having "ulimit -n" set to 1000000 at the OS level, the memsql executor has only 1024 file handles available, which fails when reading concurrently from memsql. How can we increase the limit for memsql executor?

**Comment by choochootrain** [comment]
you may have to pass that as an option in the docker run params - they recently added a `--ulimit` option which should let you do this. i'm not too familiar with how docker does it but there are security implications so docker may not let you set it to a large number.

**Comment by Vlad777** [comment]
Since we're running within the context of Mesos, wouldn't this need to be done within the Dockerfile when building the image?
"docker run" is not used here, but this instead: https://github.com/memsql/memsql-mesos/blob/master/memsql_framework/scheduler/scheduler.py#L254 ?

**Comment by choochootrain** [comment]
ulimit needs to be set at runtime, not in the Dockerfile. In the mesos world, you can pass args to the underlying `docker run` command when you create the task. 
Here is an example of where we are effectively passing `--net=host` to the docker driver: https://github.com/memsql/memsql-mesos/blob/master/memsql_framework/scheduler/scheduler.py#L122

i'm not up to date on mesos, but if it is tracking docker the `ulimit` option should also be exposed. i believe there are thrift schemas which show all the options that mesos understands.

**Comment by Vlad777** [comment]
Traced this to our own code that was setting the -DOCKER_OPTIONS='"--default-ulimit nofile=1024:4096"'
